import "@/app/globals.css";
import { NextAuthProvider } from "@/app/providers";
import { authOptions } from "@/lib/auth";
import { getServerSession } from "next-auth";
import {ReduxStoreProvider} from "@/app/Redux/ReduxStoreProvider";
import {debugLog} from "@/utils/helperFunctions";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await getServerSession(authOptions);

	return (
		<html lang="en" className="h-full dark:bg-gray-900 dark:text-white">
			<body className="h-full">
				<NextAuthProvider session={session}>
					<ReduxStoreProvider>
						{children}
					</ReduxStoreProvider>
				</NextAuthProvider>
			</body>
		</html>
	);
}
